# Generated by Django 4.2.2 on 2023-08-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
    ]
