# Generated by Django 4.2.2 on 2023-07-07 16:34

import apps.forum.models.school
import apps.forum.models.section
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_school',
            field=models.ForeignKey(default=apps.forum.models.school.School.get_default_school, on_delete=models.SET(apps.forum.models.school.School.get_default_school), to='forum.school'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.ForeignKey(default=apps.forum.models.section.Section.get_default_section, on_delete=models.SET(apps.forum.models.section.Section.get_default_section), to='forum.section'),
        ),
    ]
